Repository pagopa/pagopa-ecommerce-helpdesk-commands-service, pull requests merged in 2024-08, with the labels that each got.

#15 feat: CHK-3084 add deploy pipeline in dev
  .devops/azure-templates/api-tests.yml
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/deploy-pipelines.yml
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/config/NpgPspsApiKeyConfigBuilder.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/utils/NpgApiKeyConfiguration.kt
  src/main/resources/application.properties
Labels: minor, chart-minor, size/large

#14 [CHK-3102] feat: add docker-compose.yml with mock api npg
  .env.example
  README.md
  docker-compose.yml
  npg-mock/Dockerfile.npg-mock
  npg-mock/middleware.js
  npg-mock/npg-server.json
  npg-mock/routes.json
Labels: size/small, minor, chart-minor

#6 [CHK-3086] configure logging
  .env.example
  .gitignore
  api-spec/v1/openapi.yaml
  build.gradle.kts
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/logback-spring.xml
  src/test/resources/application.properties
Labels: size/small, minor, chart-minor

#12 [CHK-3092] feat: new postman test api collection
  api-tests/env/helpdeskcommands_dev.env.json
  api-tests/env/helpdeskcommands_local.env.json
  api-tests/env/helpdeskcommands_uat.env.json
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.local.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
Labels: minor, chart-minor, size/large

#17 [CHK-3125] feat: add integration test into code-review
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#16 [CHK-3124] feat: added client IP in the logger of the controller
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/client/NpgClient.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/services/CommandsService.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/controller/CommandsControllerTest.kt
Labels: size/small, minor, chart-minor

#18 [CHK-3127] fix: add X-Forwarded-For header into collections
  api-tests/env/helpdeskcommands_dev.env.json
  api-tests/env/helpdeskcommands_local.env.json
  api-tests/env/helpdeskcommands_uat.env.json
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.local.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
Labels: chart-patch, patch

#20 [CHK-3138] fix: convert transactionId into UUID before send as idempotenceKey
  src/main/kotlin/it/pagopa/helpdeskcommands/client/NpgClient.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/services/CommandsService.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/utils/TransactionId.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/services/CommandsServiceTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/utils/TransactionIdTest.kt
Labels: size/small, minor, chart-minor

#19 feat(pipeline): CHK-3140 pipeline uat prod
  .devops/deploy-pipelines.yml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: chart-patch, size/large, patch

#22 fix: Environment api test for DEV env
  api-tests/env/helpdeskcommands_dev.env.json
Labels: chart-patch, size/small, patch

#24 fix: enable semantic release increment version task
  build.gradle.kts
Labels: chart-patch, size/small, patch

#25 fix: remove psps on PROD
  helm/values-prod.yaml
Labels: chart-patch, size/small, patch

#26 [CHK-3145] Fix log of class object instead of UUID
  build.gradle.kts
  src/main/kotlin/it/pagopa/helpdeskcommands/services/CommandsService.kt
Labels: size/small, minor, chart-minor

#27 fix: add refundRequestDto config for native compile
  src/main/kotlin/it/pagopa/helpdeskcommands/config/WebClientConfig.kt
Labels: size/small, minor, chart-minor

#29 fix: Conf for prod env
  helm/values-prod.yaml
Labels: chart-patch, size/small, patch

#30 fix: disable apple pay and satispay
  helm/values-prod.yaml
Labels: size/small

#31 [CHK-3169] feat: return npg error messages to client
  api-tests/env/helpdeskcommands_dev.env.json
  api-tests/env/helpdeskcommands_local.env.json
  api-tests/env/helpdeskcommands_uat.env.json
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.local.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
  docker-compose.yml
  src/main/kotlin/it/pagopa/helpdeskcommands/client/NpgClient.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/NpgClientException.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/services/CommandsServiceTest.kt
Labels: minor, chart-minor
