Repository pagopa/pagopa-ecommerce-helpdesk-commands-service, pull requests merged in 2024-10, with the labels that each got.

#32 [PPABV-1] chore: readme update with WSL info
  README.md
Labels: documentation, ignore-for-release, size/small

#34 [PPABV4] update openapi
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/HelpDeskCommandsTestUtils.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/controller/CommandsControllerTest.kt
Labels: size/small, minor, chart-minor

#35 [PPABV-6] Add forwarder client + test
  build.gradle.kts
  src/main/kotlin/it/pagopa/helpdeskcommands/client/NodeForwarderClient.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/NodeForwarderClientException.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/client/NodeForwarderClientTest.kt
Labels: size/small, minor, chart-minor

#36 [PPABV-5] url to psp mapping from commons
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/RedirectConfigurationException.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/RedirectConfigurationType.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/utils/RedirectKeysConfiguration.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/helpdeskcommands/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/exceptions/RedirectConfigurationTypeTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/utils/RedirectKeysConfigurationTest.kt
  src/test/resources/application.test.properties
Labels: size/small, minor, chart-minor

#37 [PPABV-12]fix: add action field to refund redirect request dto
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/HelpDeskCommandsTestUtils.kt
Labels: size/small, minor, chart-minor

#38 [PPABV-13] Add configuration for client forwarder
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/config/WebClientConfig.kt
  src/main/resources/application.properties
  src/test/resources/application.test.properties
Labels: size/small, minor, chart-minor

#41 [PPABV-14] Add redirect mock
  README.md
  docker-compose.yml
  psp-mock/Dockerfile.psp-mock
  psp-mock/middleware.js
  psp-mock/psp-server.json
  psp-mock/routes.json
  psp-mock/set-polyfill.js
Labels: size/small, minor, chart-minor

#39 PPABV-7 business logic per esecuzione storno redirect psp tramite for…
  api-spec/client/openapi/redirect/redirect-api.yaml
  build.gradle.kts
  src/main/kotlin/it/pagopa/helpdeskcommands/config/RedirectConfigurationBuilder.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/BadGatewayException.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/RefundNotAllowedException.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/services/CommandsService.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/client/NodeForwarderClientTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/controller/CommandsControllerTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/services/CommandsServiceTest.kt
Labels: minor, chart-minor, size/large

#40 [PPABV-8] add api for local and dev/uat pipeline testing
  .env.example
  api-tests/env/helpdeskcommands_dev.env.json
  api-tests/env/helpdeskcommands_local.env.json
  api-tests/env/helpdeskcommands_uat.env.json
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.local.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
  src/main/kotlin/it/pagopa/helpdeskcommands/utils/PaymentMethod.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/HelpDeskCommandsTestUtils.kt
Labels: minor, chart-minor, size/large

#44 [PPABV-9] feat: update integration test on CR pipeline
  .devops/code-review-pipelines.yml
Labels: size/small, minor, chart-minor

#42 [PPABV-19] add user and client IP to request header
  api-spec/v1/openapi.yaml
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.local.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/controller/CommandsControllerTest.kt
Labels: size/small, minor, chart-minor

#43 [PPABV-15] fix: deleted action field in refund redirect api
  api-spec/v1/openapi.yaml
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.local.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
  src/test/kotlin/it/pagopa/helpdeskcommands/HelpDeskCommandsTestUtils.kt
Labels: size/small, minor, chart-minor
