Repository pagopa/pagopa-ecommerce-helpdesk-commands-service, pull requests merged in 2025-06, with the labels that each got.

#61 feat: [CHK-4169] add mongo configuration
  .devops/code-review-pipelines.yml
  .env.example
  build.gradle.kts
  docker-compose.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/config/EcommerceMongoRepositoryConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/MongoEcommerceConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/repositories/TransactionsEventStoreRepository.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/repositories/TransactionsViewRepository.kt
  src/main/resources/application.properties
  src/test/resources/application.test.properties
Labels: size/small, minor, chart-minor

#58 feat(event-queues): [CHK-4170] add azure queue config and message sending logic
  .env.example
  README.md
  build.gradle.kts
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/client/AzureApiQueueClient.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/AzureStorageAotConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/AzureStorageConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/QueueEventMixin.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/TransactionEventResolverNativeConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/properties/QueueConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/services/TransactionEventService.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/services/TransactionEventServiceInterface.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/helpdeskcommands/client/DirectAzureQueueClientTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/config/AzureStorageConfigTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/services/TransactionEventServiceTest.kt
  src/test/resources/application.test.properties
Labels: minor, chart-minor, size/large

#62 feat: [CHK-4171] new apis refund notification
  .devops/code-review-pipelines.yml
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/helpdeskcommands/client/AzureApiQueueClient.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/config/EcommerceCommonsReflectionConfig.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/controllers/CommandsController.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/InvalidTransactionStatusException.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/TransactionNotFoundException.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/exceptions/TransactionNotRefundableException.kt
  src/main/kotlin/it/pagopa/helpdeskcommands/services/TransactionEventService.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/HelpDeskCommandsTestUtils.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/controller/CommandsControllerTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/helpdeskcommands/services/TransactionEventServiceTest.kt
Labels: minor, chart-minor, size/large

#63 feat(test-api): [CHK-4239] add apis to test collection
  README.md
  api-tests/env/helpdeskcommands_dev.env.json
  api-tests/env/helpdeskcommands_local.env.json
  api-tests/env/helpdeskcommands_uat.env.json
  api-tests/v1/helpdeskcommands.api.tests.dev.json
  api-tests/v1/helpdeskcommands.api.tests.event-based.json
  api-tests/v1/helpdeskcommands.api.tests.uat.json
Labels: minor, chart-minor, size/large

#64 feat(integration-tests): [CHK-4172] add ecommerce-local integration
  .devops/code-review-pipelines.yml
  README.md
  build.gradle.kts
  src/main/kotlin/it/pagopa/helpdeskcommands/services/TransactionEventService.kt
Labels: documentation, size/small, minor, chart-minor
